name: Junior J Free School
description: "Welcome to our website!  We are a traditional children's school which combines the proven ideals and standards of old, with the innovative teaching techniques and technology of new."
keywords: IRC, stormbit, anime, gaming, chat
paginate: 5,
paginate_path: /news/:num
base: http://jjfree.dev/
permalink: /news/:year/:month/:day/:title/index.html
encoding: UTF-8
markdown: redcarpet
redcarpet:
    extensions: [
        "no_intra_emphasis",
        "fenced_code_blocks",
        "tables",
        "strikethrough"
    ]
highlighter: false

# Default behaviour in Jekyll 2.0
relative_permalinks: false

# Navigation menu.
navmenu: {
	'News': '/news/',
    'About us': {
        'About our school': '/about-us/about-jjfree/',
        'Gallery': '/about-us/gallery/',
    },
    'Tools': {
    	'Tools': '/tools/index.html',
    	'Report an absence': '/tools/report-absence/',
    },
    'Departments': {
        'Departments': '/about-us/departments/index.html',
        'Art': '/about-us/departments/art/',
        'PE': '/about-us/departments/pe/',
    }
}

# Author metadata.
authors:
    alex: {
        "name": "Alex",
    }

# CSS Stylesheets to be included in the header.
styles:
    - "/css/bootstrap.min.css"
    - "/css/blueimp-gallery.min.css"
    - "/css/bootstrap-image-gallery.min.css"
    - "/css/alex.css"

# Javascript files to be included in the header.
scripts:
    - "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
    - "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"
    - "/js/jquery.blueimp-gallery.min.js"
    - "/js/bootstrap-image-gallery.min.js"
    - "/js/alex.js"
